### ISSUE TITLE
sxiv [url]

### ISSUE THREAD

**Issue by explosion-mental** [bakkeby/sxiv-flexipatch#2]
'Stream' images, like feh.
https://github.com/explosion-mental/sxiv/blob/main/patches/libcurl.patch

**Comment by bakkeby** [comment]
^ seems to work just fine

**Comment by explosion-mental** [comment]
I also liked this one https://github.com/muennich/sxiv/issues/294

**Comment by bakkeby** [comment]
Yes having a separate border around marked clients makes them easier to see (compared to a small square in the bottom right corner).

![image](https://user-images.githubusercontent.com/1438008/121366623-ebb8ae80-c939-11eb-8fae-1e7c5999d752.png)

As there were two distinct features (marked files count being shown in the bar + a border for marked clients) I decided to split these two into different toggles, `MARK_BORDER_PATCH` and `MARK_COUNT_PATCH`.

You can change the colour of the marked border by adding `Sxiv.mark` in your .Xresources file.

**Comment by bakkeby** [comment]
Oh and the [window title](https://github.com/muennich/sxiv/pull/453) patch was also very welcome, added that as well.

**Comment by explosion-mental** [comment]
> Oh and the [window title](https://github.com/muennich/sxiv/pull/453) patch was also very welcome, added that as well.

Wow haven't seen this one, looks great.
