### ISSUE TITLE
Window.c Missing Argument

### ISSUE THREAD

**Issue by sl4m75** [bakkeby/sxiv-flexipatch#3]
When trying to make without the alpha patch i get this error 
```bash
window.c:79:39: error: macro "DefaultColormap" requires 2 arguments, but only 1 given
   79 |                 DefaultColormap(e->dpy),
```
tried changing it to DefaultColormap(e->dpy,e->scr), and it seems to work

**Comment by bakkeby** [comment]
Thanks for that and terribly sorry for the long delay, I clearly missed this among all the other emails.

Much appreciated.
