### ISSUE TITLE
webp images without an extension won't open

### ISSUE THREAD

**Issue by soystemd** [bakkeby/sxiv-flexipatch#6]
sxiv can open jpg and png images without any extension (.jpg, .png) at the end, 
but it fails for webp images.

**Comment by bakkeby** [comment]
Yes it does this also in the base sxiv.

This happens if the Imlib2 library is not able to determine the file format based on the file header.  Not sure of the likelihood of someone adding a fix for that in the Imllib2 library though.

**Comment by bakkeby** [comment]
In other news the guys working on nsxiv have been refactoring and improving on animated webp support for the viewer, which incidentally also addresses the issue of opening extensionless webp images. I may end up copying those improvements in when they are ready.

**Comment by N-R-K** [comment]
>  but it fails for webp images.

It fails for extension-less gif and tiff too.

> This problem was just fixed in git (yesterday). It was a regression since 1.6.x.
> Imlib2 uses the file name extension only as a first guess. After that it tries all loaders.
> All loaders do signature checks like you describe.

https://phab.enlightenment.org/T8957#155990

The `is_webp` workaround currently on nsxiv should fix it for webp until the new imlib2 version releases.

**Comment by N-R-K** [comment]
@soystemd if you're on a rolling release distro then you can try out `Imlib2 v1.7.4` , the issue with extensionless images is fixed there.

**Comment by demurky** [comment]
> @soystemd if you're on a rolling release distro then you can try out `Imlib2 v1.7.4` , the issue with extensionless images is fixed there.

it is fixed indeed, thanks for the info!
